FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# CGO_ENABLED=0 creates a statically linked binary for alpine
RUN CGO_ENABLED=0 go build -o /app/producer ./cmd/producer/

FROM alpine:3.20
WORKDIR /root/

RUN apk --no-cache add ca-certificates

COPY --from=builder /app/producer .

ENTRYPOINT ["./producer"]
