# # Infrastructure Settings
# storage_type: "postgres"
# publisher_type: "nats"

# # Connection Strings
# storage_url: "postgres://postgres:postgres@localhost:5432/postgres"
# publisher_url: "nats://localhost:4222"

# # Performance Tuning
# poll_interval: "500ms"
# batch_size: 50

# # API Settings
# server_port: ":9000"

publisher_type: "redis"
publisher_url: "redis://localhost:6379"