---

volumes:
  pg_data: {}
  redis_data: {}
  nats_data:

services:

  postgres:
    image: postgis/postgis:16-3.4
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    command: 
      - "postgres"
      - "-c max_wal_size=2GB"      
      - "-c min_wal_size=512MB"
      - "-c checkpoint_timeout=5min"
      - "-c archive_mode=off"

  nats:
    image: nats:latest
    ports:
      - "4222:4222" 
      - "8222:8222" 
    # -js enables JetStream, -sd sets storage directory
    command: ["-js", "-sd", "/data", "-m", "8222"] 
    volumes:
      - nats_data:/data

  nats-box:
    image: natsio/nats-box
    entrypoint: sleep infinity # Keeps it alive so you can "exec" into it
    networks:
      - default

  relay:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env

  redis:
    image: redis:6-alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 16686:16686

  prometheus:
    image: prom/prometheus:v3.1.0 # Using a 2026-current stable version
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-otlp-receiver' # Crucial for modern OTel ingestion
      # - '--web.enable-remote-write-receiver' # Crucial for modern OTel ingestion

    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml


  otel-collector:
    image: otel/opentelemetry-collector:0.149.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
