-- =============================================================================
-- Open Outbox Core Schema
-- =============================================================================
-- This schema is optimized for high-concurrency "At-Least-Once" delivery.
-- It uses partial indexes to minimize overhead and Postgres-specific types
-- (UUID, BYTEA, JSONB) for maximum efficiency and flexibility.
-- =============================================================================

-- Safety: Clear existing structure for development/migrations.
DROP TABLE IF EXISTS outbox_events CASCADE;

CREATE TABLE outbox_events (
    -- Unique identifier for the event. Usually generated by the application
    -- to allow for idempotent inserts.
    event_id      UUID PRIMARY KEY,

    -- Categorizes the message (e.g., 'user.created', 'order.placed').
    -- Useful for publishers to route messages to specific topics/subjects.
    event_type    TEXT NOT NULL,

    -- Optional key used to ensure message ordering in systems like Kafka or NATS.
    -- Messages with the same partition_key are usually routed to the same consumer.
    partition_key TEXT,

    -- The raw message body. Stored as BYTEA (binary) to remain agnostic of
    -- serialization formats like JSON, Protobuf, or Avro.
    payload       BYTEA NOT NULL,

    -- Extensible metadata container for tracing (e.g., span IDs),
    -- content-type, or custom application headers.
    headers       JSONB NOT NULL DEFAULT '{}',

    -- Lifecycle state machine:
    -- PENDING:    Ready for pickup.
    -- DELIVERING: Currently locked by a relay instance (lease active).
    -- DELIVERED:  Successfully published to the broker.
    -- DEAD:       Exceeded max retries; requires manual intervention.
    status        TEXT NOT NULL DEFAULT 'PENDING',

    -- Tracks how many times publishing has been attempted.
    attempts      INT NOT NULL DEFAULT 0,

    -- Stores the error message from the last failed attempt for debugging.
    last_error    TEXT,

    -- The "Next Run" timestamp. Supports scheduled events and exponential backoff.
    -- The relay will not pick up events until NOW() >= available_at.
    available_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Identity of the relay instance that currently holds the lock.
    -- Prevents multiple relays from processing the same event.
    locked_by     TEXT,

    -- Timestamp when the current lock was acquired. Used by the "Reaper"
    -- to identify and reset abandoned leases (stuck processes).
    locked_at     TIMESTAMPTZ,

    -- When the event reached its final successful state. Useful for auditing and pruning.
    delivered_at  TIMESTAMPTZ,

    -- Standard audit timestamps.
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Strict enforcement of the state machine values.
    CONSTRAINT check_valid_status CHECK (
        status IN ('PENDING', 'DELIVERING', 'DELIVERED', 'DEAD')
    )
);

-- -----------------------------------------------------------------------------
-- PERFORMANCE INDEXES (The "Critical Path")
-- -----------------------------------------------------------------------------

-- The "Pickup" Index: Essential for ClaimBatch.
-- It allows the Relay to find the oldest available PENDING events without a full table scan.
-- The partial index keeps it extremely fast even as the table grows.
CREATE INDEX IF NOT EXISTS idx_outbox_processing_queue
    ON public.outbox_events (available_at ASC, created_at ASC)
    WHERE status = 'PENDING';

-- The "Reaper" Index: Used to find events stuck in 'DELIVERING' state.
-- Allows the background reaper task to quickly find and reset expired leases.
CREATE INDEX IF NOT EXISTS idx_outbox_stuck_leases
    ON public.outbox_events (locked_at ASC)
    WHERE status = 'DELIVERING';

-- -----------------------------------------------------------------------------
-- TELEMETRY INDEXES (Optimizing for GetStats)
-- -----------------------------------------------------------------------------

-- Optimizes the COUNT query for pending messages.
CREATE INDEX IF NOT EXISTS idx_outbox_metrics_count
    ON public.outbox_events (status)
    WHERE status = 'PENDING';

-- Optimizes the "Oldest Age" query by allowing the DB to find the minimum
-- created_at within the PENDING subset.
CREATE INDEX IF NOT EXISTS idx_outbox_metrics_lag
    ON public.outbox_events (status, created_at ASC)
    WHERE status = 'PENDING';
